const path = require("path");
const fs = require("fs");
const LUA_LOCATION = path.join(__dirname, "../lua");

function main () {
  const header = [
    "// NOTE -- THIS FILE IS AUTOGENERATED! DO NOT EDIT DIRECTLY",
    "package redisched",
  ];

  const fullContents = header.concat(
    fs.readdirSync(LUA_LOCATION)
      .filter(f => f.endsWith(".lua"))
      .map(f => {
        const contents = fs.readFileSync(path.join(LUA_LOCATION, f), "utf8").replace(/`/g, "'");
        const varName = `Redis${capitalizeFirstLetter(f.slice(0, -4))}Script`;
        const comment = `// ${varName} script`; // comment for exported const, avoid linter warnings :/
        return [comment, `const ${varName} = \`${contents}\``].join("\n");
      })
  ).join("\n\n");

  fs.writeFileSync(path.join(__dirname, "../golang/pkg/redis_scripts.go"), fullContents);
}

module.exports = main;
if (module.parent == null) main();

function capitalizeFirstLetter (str) {
  return str[0].toUpperCase() + str.slice(1);
}
